# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24589768096de35821d9d9a492101a8cb8c34ac4a19b71000c6dcc2b2519d65c33b246e0ef7c162ecb1db2f97dfc9b17dbbcebec1880db7369230909813c2264

test:
  secret_key_base: 681a5f346142abd6db0e1f5fdc4b89cbddb0d51d02baf459de5fa08eee5f184c70df085e86f213bab7be3e6795d82f9dba1edbb503260c295dc58d5b05e2e4e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
